### ISSUE TITLE
Make activity graphs cover longer time period

### ISSUE THREAD

**Issue by thedamon** [netlify/staticgen#118]
I think the issue/star/forks graphs would be more useful if they covered months instead of days!

Any reason for them not to?

**Comment by bdougie** [comment]
Seems valid and would happily accept this change in the https://github.com/netlify/staticgen/blob/master/github/api.rb

The only concern would be for newer libraries that don't have months of life and render a monthly graph useless. Perhaps it would be more ideal to have a toggle to change the scope of the graph.

**Comment by erquhart** [comment]
We've dropped the graphs, but are now ramping up data collection to cover at least the last 90 days. Closing.
