### ISSUE TITLE
The weekly changes for stars, forks, and issues are all zero

### ISSUE THREAD

**Issue by MateusAmin** [netlify/staticgen#183]
If you do a weekly reset please change to a rolling week ( past 7 days)! If it is a bug, please fix. :)

Thanks for your consideration.

**Comment by fool** [comment]
I think I fixed this, but we won't know until a build runs with enough time elapsed between builds (it is built every morning at 10) for some stars or forks to happen.  Cause:  missing GIST_ID in our build environment :facepalm:
