### ISSUE TITLE
Remove Unmaintained Static Site Generators?

### ISSUE THREAD

**Issue by RyanZim** [netlify/staticgen#188]
Wouldn't it be a good idea to remove some of the unmaintained static site generators?

Perhaps open an issue in the repositories that haven't had commit activity within the past ~6 months, clearly stating that if no reply is received, it will be removed from www.staticgen.com.

If the issue is not replied to within _n_ days, remove it.

This would allow new, but actively maintained libraries to get noticed instead of being mixed with abandoned libraries that never took off. Thoughts?

I could possibly help with some of this.

**Comment by RyanZim** [comment]
@biilmann bump

**Comment by rybit** [comment]
I think that there is still value in having them listed. Either as references for new development or just a history. 

That being said we would consider PRs that used the github api to visually mark something as stale. Open to ideas here, but closing this issue for the time being.
