### ISSUE TITLE
new copy 

### ISSUE THREAD

**Issue by ChrBach** [netlify/staticgen#212]
New headline: Get started with 1 click

New copy: 
Introducing the “Deploy to Netlify” button on select generators to help you deploy new sites from generator-specific templates with a single click. Get a site up in minutes, with custom domain, HTTPS and continuous delivery completely free of charge. (Want your own Deploy to Netlify button? [Learn more here](https://www.netlify.com/docs/deploy_button/))

**Comment by cassandraoid** [comment]
No longer relevant.
