### ISSUE TITLE
Change in stats from last week look broken

### ISSUE THREAD

**Issue by plaindocs** [netlify/staticgen#236]
None of the projects have any change data.

**Comment by hbakhtiyor** [comment]
what maybe issue?

**Comment by rdwatters** [comment]
Seems to be the case as of 2017-06-14 as well. Hmmm...

**Comment by fool** [comment]
when the site doesn't build every day, the stats are broken until it builds again daily for a week.   The build was broken for a few days til this morning.  Fixes to this behavior are welcome :)

**Comment by plaindocs** [comment]
An easy but ugly fix would be a daily cron build...

**Comment by fool** [comment]
we do that already.  

The site build breaks without constant maintenance - every time a repository that we list moves, the build breaks.  A fix against that is needed.  

You can see the fail mode if you change a repo path in a source/projects/x.md file to something old (e.g. revert today's change from spf13/hugo to gohugoio/hugo and try the build and you'll see what fails)

**Comment by rdwatters** [comment]
Ahhhhhhh, sh&$. Didn't even think about notifying the good folks at Netlify of the org change for this site. Sorry about that, and thanks for updating, @fool

**Comment by fool** [comment]
fear not @rdwatters it wasn't *just* hugo and someone actually did PR it this morning ;)
