### ISSUE TITLE
bundle install doesn't work

### ISSUE THREAD

**Issue by digitalbricklayer** [netlify/staticgen#276]
I have cloned the repo following the instructions on the project home page. When running the `bundle install` command I get the following error whilst the system is trying to install the json gem:

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /tmp/bundler20170622-3451-iadfh9json-1.8.1/gems/json-1.8.1/ext/json/ext/generator
/usr/bin/ruby2.3 -r ./siteconf20170622-3451-fln4n8.rb extconf.rb
creating Makefile

current directory: /tmp/bundler20170622-3451-iadfh9json-1.8.1/gems/json-1.8.1/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /tmp/bundler20170622-3451-iadfh9json-1.8.1/gems/json-1.8.1/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
In file included from generator.c:1:0:
../fbuffer/fbuffer.h: In function ‘fbuffer_to_s’:
../fbuffer/fbuffer.h:175:47: error: macro "rb_str_new" requires 2 arguments, but only 1 given
     VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                               ^
../fbuffer/fbuffer.h:175:20: warning: initialization makes integer from pointer without a cast [enabled by default]
     VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                    ^
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /tmp/bundler20170622-3451-iadfh9json-1.8.1/gems/json-1.8.1 for inspection.
Results logged to /tmp/bundler20170622-3451-iadfh9json-1.8.1/extensions/x86_64-linux/2.3.0/json-1.8.1/gem_make.out

An error occurred while installing json (1.8.1), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.1'` succeeds before bundling.

In Gemfile:
  middleman was resolved to 3.3.2, which depends on
    uglifier was resolved to 2.5.0, which depends on
      json

The problem has been fixed in json 1.8.2.

**Comment by bdougie** [comment]
I upgraded to middleman 3.4.0 and it seems to work fine. Thanks for the heads up.
