### ISSUE TITLE
'All languages' selection in the language dropdown not working

### ISSUE THREAD

**Issue by mitchellcash** [netlify/staticgen#345]
If you drop down the language selection and select a language, when go back and select 'All languages' to remove the filter it has no impact and the page remains filtered on the last language you selected.

**Steps to Reproduce**

1. Drop down the language selection and select a language
2. Go back and select 'All languages'

![](https://user-images.githubusercontent.com/8009243/37446497-fdc0bb10-2868-11e8-86c8-ac181e41dc34.gif)

**Comment by erquhart** [comment]
Regression from #327.

@dracos would you mind taking a look?

**Comment by dracos** [comment]
PR at #346
