### ISSUE TITLE
Sort issue broken – sorting by forks and back by stark misses entries [Bug]

### ISSUE THREAD

**Issue by bentolor** [netlify/staticgen#347]
# Actual behavior

1. Go to https://www.staticgen.com/
2. Remember to entries: Jekyll, Hugo, ...
3. Apply "sort by Forks": Hubpress, Hexo, ...
4. Select back Sort by start: Hexo, Gatsby, … 

Even more Jekyll, Hugo etc. seem to miss completely from the list

# Expected behavior
1. Sorting results should be stable
2. Site should not randomly drop entries

**Comment by erquhart** [comment]
I can't reproduce. What browser/OS are you using?

**Comment by bentolor** [comment]
Current Firefox i.e. on Ubuntu

![https://i.imgur.com/Ivx9KRP.gif](https://i.imgur.com/Ivx9KRP.gif)

**Comment by erquhart** [comment]
Really strange - this doesn't happen in Chrome, but does happen in Firefox and Safari.

Even stranger, Safari takes a few seconds before rendering each change in sort.

We need to move this site over to utilize React Static using the updated headlesscms.org (https://github.com/netlify/headlesscms) as a template.

**Comment by Clindbergh** [comment]
I cannot even get the filters to work on neither Firefox, Edge, Chrome or IE on Windows.

![grafik](https://user-images.githubusercontent.com/2742027/39949542-9ea13a70-557b-11e8-8be7-21c9efd201b6.png)

It would always show the default order with no filter.

**Comment by erquhart** [comment]
I can't reproduce. I'm on Mac using Chrome and Firefox, and an iPhone, works everywhere. Can you check again?

**Comment by Clindbergh** [comment]
Sorry, this works now. I don't know what the problem was.
