### ISSUE TITLE
Plugins and Extensions data

### ISSUE THREAD

**Issue by MatheusRV** [netlify/staticgen#367]
It is extremely important to map out the extensions that the SSG may have, I believe that the ideal moment for this discussion is now, what do you think?

Jekyll, for example, has a large community of plugins and few places have all mapped ..

**Comment by erquhart** [comment]
That'd be a bit much for this site, I'd recommend checking out the Awesome Jekyll Plugins list for that: https://github.com/planetjekyll/awesome-jekyll-plugins
