### ISSUE TITLE
Nuxt deploy to Netlify error

### ISSUE THREAD

**Issue by MartinX3** [netlify/staticgen#374]
Used this function to create a basic project.
Deploy results in an error

```
7:12:13 PM:  + 3 hidden assets
7:12:13 PM: ERROR in ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":false,"presets":[["/opt/build/repo/node_modules/babel-preset-vue-app/dist/index.common.js",{"targets":{"ie":9,"uglify":true}}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./layouts/default.vue
7:12:13 PM: Module not found: Error: Can't resolve '~components/Footer.vue' in '/opt/build/repo/layouts'
7:12:13 PM:  @ ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":false,"presets":[["/opt/build/repo/node_modules/babel-preset-vue-app/dist/index.common.js",{"targets":{"ie":9,"uglify":true}}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./layouts/default.vue 9:0-46
7:12:13 PM:  @ ./layouts/default.vue
7:12:13 PM:  @ ./.nuxt/App.js
7:12:13 PM:  @ ./.nuxt/index.js
7:12:13 PM:  @ ./.nuxt/client.js
7:12:13 PM:  ERROR
7:12:13 PM:   Error: Webpack build exited with errors
7:12:13 PM:   
```

**Comment by erquhart** [comment]
This is the repo for staticgen.com. Maybe check out Nuxt community support?

**Comment by MartinX3** [comment]
It is reported since  25 Dec 2017.
The last reaction from the repo owner was 27 Mar 2017.
You should remove this repo from your side, because it is no longer supported by the repo owner.

I was able to create my own starter.
Can I contribute it to you?

**Comment by erquhart** [comment]
Ah, didn't realize you were referring to the starter. We definitely want working starters - does yours use Nuxt?

**Comment by MartinX3** [comment]
Woopsi, sorry
I did mean nuxt.js with vuetify, google material icons, eslint and a example page.
I wrote vue.js because nuxt.js is a static vue.js.

**Comment by erquhart** [comment]
It just needs to be a repo that can be cloned and deployed as is, and produces a template site that can be customized by the developer.
