### ISSUE TITLE
Builds failing

### ISSUE THREAD

**Issue by zeroby0** [netlify/staticgen#400]
Hi, looks like something is wrong somewhere.

Please check [pull request 399](https://github.com/netlify/staticgen/pull/399)

I've tried content from previous working builds and they too failed. For example, I've tried building with [Hugo's](https://www.staticgen.com/hugo) content, but with the `Title: Hugos`to not create a clash with URLs and [it failed too](https://github.com/netlify/staticgen/pull/399/commits/5e63f850c210553ca1e5e13d2dd6f908eacfacb8).

If possible, please add a [build status badge](https://github.com/dwyl/repo-badges) to the readme so that we know if the build is failing due to contribution or the projects original code.

Thank you.
Aravind.

**Comment by cekvenich** [comment]
+1. I just did a PR for 'metabake', it failed, I assume for same reason.

**Comment by erquhart** [comment]
Fixed in #411.
