### ISSUE TITLE
Possible caching issue

### ISSUE THREAD

**Issue by MitchellCash** [netlify/staticgen#422]
I've been playing around with this project locally and have come across a possible issue.

1. `git clone https://github.com/netlify/staticgen`
2. `npm install`
3. `npm start`
4. Delete one or more files from the `projects` folder
5. Refresh browser and see deleted projects still visible on the homepage
6. Stop development server
7. Delete the GitHub Gist `staticgen-archive.json`
8. Delete `tmp` and `dist`
9. `npm start`
10. Note the deleted projects are still visible on the homepage
11. Note the deleted project data still exists in the newly generated `tmp` and Gist caches. I have no idea where it keeps pulling the deleted project data from to generate those `JSON` caches.

If I click on a deleted project on the homepage it will show an error (`TypeError: _react2.default.createRef is not a function`) rather than a 404 page.

Node version: v9.4.0
npm version: 5.6.0
Firefox 62.0
macOS 10.13.6

**Comment by erquhart** [comment]
That just happens locally, it's a bug in react-static. If you make a change to a javascript file while the dev server is running, it will refresh the cache. A more recent version of react-static probably addresses this as well, we should update at some point.
