### ISSUE TITLE
GitHub stats missing for Gatsby

### ISSUE THREAD

**Issue by chmac** [netlify/staticgen#428]
When I look at staticgen.com in either Chrome or Firefox, I don't see any of the GitHub stats for Gatsby. That also has the effect of putting it at the bottom of the list, while it's actually in the top 5 most popular static site generators by GitHub stars.

**Comment by philhawksworth** [comment]
I'm not seeing this issue @chmac. Are you still able to reproduce this?

**Comment by chmac** [comment]
@philhawksworth Nope, seems to be resolved. Maybe it was a temporary error during a build or something. Thanks for following up.
