### ISSUE TITLE
add Quart

### ISSUE THREAD

**Issue by illucent** [netlify/staticgen#436]
Hi! Please add Quart; an ASGI alternative to Flask
https://gitlab.com/pgjones/quart

**Comment by pgjones** [comment]
Thanks for thinking of Quart, but it isn't really a static site generator. Quart is similar to Flask, and I think there would need to be a Frozen-Quart (like Frozen-Flask) to join this list.

**Comment by philhawksworth** [comment]
Thanks both. It does sound like Quart is not quite suitable for this lost, but if you have examples of using Frozen-Quart and it seems appropriate as an SSG, then feel free to raise a PR to contribute.

Details for contributions here: https://www.staticgen.com/contribute
