### ISSUE TITLE
Would it be possible to add sort by "stars growth"

### ISSUE THREAD

**Issue by mansona** [netlify/staticgen#513]
Hey folks 👋 

I find the way that you're displaying the growth of stars by product very interesting and very useful 🎉 I'm wondering if it's possible to add sorting by "stars growth" to the sort dropdown 🤔 

I took a quick look at the implementation and it seems a bit complicated at first glance. If it is something that you think might be interesting to add then I might take another look at it 👍

**Comment by erquhart** [comment]
The plan has been to implement the same sorting we have on headlesscms.org - that site also uses React Static, just hasn't been updated for trending sort: https://github.com/netlify/headlesscms.org
