### ISSUE TITLE
Broken github repo links in projects added since 07/23

### ISSUE THREAD

**Issue by dmbaturin** [netlify/staticgen#534]
The link to the github repo is treated as relative and https://github.com is not appended to the URL. Docsify for example has `href="docsifyjs/docsify"`, thus the link is to https://www.staticgen.com/docsifyjs/docsify

Affected pages:
* https://www.staticgen.com/haunt
* https://www.staticgen.com/docsify
* https://www.staticgen.com/soupault

At first I thought I've messed up the repo field, but then I checked that everything else also uses relative "user/repo" link in that field, but only projects merged in yesterday are affected.

**Comment by erquhart** [comment]
Thanks for catching this. The site just has issues, and it looks like React Static may not be moving forward anymore as a project. Locking staticgen.com to the current deploy until we can get over to a different SSG, probably Gatsby.
