### ISSUE TITLE
Migrate to Gatsby

### ISSUE THREAD

**Issue by erquhart** [netlify/staticgen#541]
It may be time to move this project to Gatsby. The migration would impact this repo as well as [headlesscms.org](https://github.com/netlify/headlesscms.org).

I'd expect it to look something like this:

1. Migrate Twitter, GitHub, and GitLab data fetching logic to proper Gatsby source plugins (use headlesscms.org source for this)
2. Create a Gatsby Theme based on the components used in headlesscms.org (updated most recently)
3. Update both staticgen and headlesscms.org to use the new theme and plugins

Have not vetted this plan fully, more consideration is needed before someone jumps in.

**Comment by ZoltanVeres** [comment]
Would love to help you out on this one. Let me know if you need a hand.

**Comment by erquhart** [comment]
@ZoltanVeres if you're interested, that ^^ is the plan - let me know what you want to do!
