### ISSUE TITLE
PR of project accepted: but not reflected on www. CDN issue?

### ISSUE THREAD

**Issue by cekvenich** [netlify/staticgen#585]
I got my PR pulled/accepted to update MetaBake name to INTUITION.DEV.
But the web site is not updated - been almost a week.

In the past when PR update to project text was pulled I don't recall a delay. But now site is not updated.
I could do another PR just to try to trigger staticgen website to update if that is a good next step.

**Comment by erquhart** [comment]
Builds are temporarily paused while we work out some bugs, it'll be updated soon.

**Comment by cekvenich** [comment]
Got it. If you know eta, that would be great. We do have the JAMstack conference coming up so ideally well before.

**Comment by noraj** [comment]
Vvery annoying it is not already fixed

**Comment by erquhart** [comment]
Very soon.

**Comment by cekvenich** [comment]
Can we get an update on the ETA?

**Comment by cekvenich** [comment]
It was deployed :-)
