### ISSUE TITLE
Bashblog-ng not showing

### ISSUE THREAD

**Issue by dvwallin** [netlify/staticgen#600]
Bashblog-ng was added in https://github.com/netlify/staticgen/commit/8226c576be15a907ff0bc946a7278df0e4632eef and later approved and merged into the repo. That is however many weeks ago and it still does not show up on the website. Bashblog-ng is a fork of Bashblog (that's already on the site) - is this somehow part of the problem?

**Comment by erquhart** [comment]
The site is locked to an older deploy until we fix some issues. It'll be updated soon.
