### ISSUE TITLE
Unable to setup local build

### ISSUE THREAD

**Issue by dildiwana** [netlify/staticgen#634]
The `README.md` document is not in sync with the current build environment used and due to this not able to setup it locally.

**Comment by akanshgulati** [comment]
@erquhart can you please loop up this issue as I am also facing same. Not able to setup the local version.

**Comment by akanshgulati** [comment]
@erquhart any update on fixing the setup of the repo?

**Comment by erquhart** [comment]
Yeah this is a known issue, addressing soon.

**Comment by kevinfs510** [comment]
I'm facing the same issue -- unable to set-up local build. Is the ReadMe.md up to date following the move to Gatsby? Similar issue with headlesscms.org
