### ISSUE TITLE
bug: sorting by language and/or by template is broke

### ISSUE THREAD

**Issue by ZoltanVeres** [netlify/staticgen#651]
Hey @erquhart !
Excellent work on #649 , i was looking into it to see what approach you choose for the migration.
I noticed a very weird bug, you prob. already know about this, but if you try to filter by language and/or by template a blank screen is happening.

The attached gif should give you enough to reproduce it, this happens on Win7 Chrome 78.0.3904.108

![staticgen2](https://user-images.githubusercontent.com/214139/69609294-d9b23c00-1031-11ea-9e58-4de235d4bdeb.gif)

**Comment by erquhart** [comment]
Thanks Zoli - fixed in #652 👍
