### ISSUE TITLE
Pull request #662 failed

### ISSUE THREAD

**Issue by jeffschwartz** [netlify/staticgen#663]
I issued pull request #662 but it failed with the following message, which I pulled from the log:

Pull request #662 failed: 9:55:23 AM:   Error: Token authentication requires a token to be set 9:55:23 AM:    9:55:23 AM:   - authenticate.js:25 authenticate 9:55:23 AM:     [repo]/[@octokit]/rest/lib/plugins/authentication/authenticate.js:25:15 9:55:23 AM:    9:55:23 AM:   - fetch-archive.js:25 authenticate 9:55:23 AM:     /opt/build/repo/scripts/fetch-archive.js:25:11 9:55:23 AM:    9:55:23 AM:   - fetch-archive.js:148 _callee7$ 9:55:23 AM:     /opt/build/repo/scripts/fetch-archive.js:148:3 9:55:23 AM:    9:55:23 AM:   - runtime.js:62 tryCatch 9:55:23 AM:     [repo]/[regenerator-runtime]/runtime.js:62:40 9:55:23 AM:    9:55:23 AM:   - runtime.js:296 Generator.invoke [as _invoke] 9:55:23 AM:     [repo]/[regenerator-runtime]/runtime.js:296:22 9:55:23 AM:    9:55:23 AM:   - runtime.js:114 Generator.prototype.(anonymous function) [as next] 9:55:23 AM:     [repo]/[regenerator-runtime]/runtime.js:114:21 9:55:23 AM:    9:55:23 AM:   - fetch-archive.js:444 step 9:55:23 AM:     /opt/build/repo/scripts/fetch-archive.js:444:191 9:55:23 AM:    9:55:23 AM:   - fetch-archive.js:444 

Not sure if this is an issue on my end or not. Appears that I need a token?

**Comment by erquhart** [comment]
Commented on the PR, you're missing a year of commits on your fork, just needs to be updated.
