### ISSUE TITLE
Fetch Twitter List Members

### ISSUE THREAD

**Issue by rishirD** [netlify/staticgen#692]
Need help. I am planning to fetch users based on a certain keyword in their bio.
For example - If I want to fetch all the developers from India, is it possible to analyze their bio with the keyword "developer" and get user details? Just to curate all the developers at one place.
or
Maybe I can manually create a list of members. And fetch user profiles from that list. That's possible, right?

**Comment by erquhart** [comment]
This is the repo for staticgen.com.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rishirD** [comment]
not valid
