### ISSUE TITLE
[Question] reason move from react-static to gasby?

### ISSUE THREAD

**Issue by adamchenwei** [netlify/staticgen#736]
I saw a PR done in react-static that, you now start using gatsby instead of react-static. May I know what is the huge advantage you gain by this conversion?
Just very curious!
https://github.com/react-static/react-static/pull/1388/files
Thanks

**Comment by erquhart** [comment]
Sure - Gatsby just has a ton of traction, things are well defined, and the ecosystem supports all kind of integrations. They also have robust theming support, so we can eventually merge the core of this repo and headlesscms.org into a single shared theme. No knock on React Static, it’s a great system.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
