### ISSUE TITLE
consider merging with staticsitegenerators.net

### ISSUE THREAD

**Issue by anarcat** [netlify/staticgen#86]
https://staticsitegenerators.net/ seems to have been there for a while and serves a similar purpose. why not merge the two?

the issue on the other side has already been opened, see https://github.com/bevry/staticsitegenerators/issues/22

**Comment by biilmann** [comment]
Hi there.

Staticgen has actually been around for quite a bit longer than staticsitegenerators.net, though the current version is more recent.

There are some really big differences between the two lists, mostly related to the rules specified here:

http://www.staticgen.com/rules

If you go through the list of staticsitegenerators.net you'll see things like BitBalloon (our drag'n drop hosting platform), Kirby (A flat file CMS), Statamatic (Proprietary flat file CMS) that are actually not static site generators and not open-source.

We prefer to keep a smaller list with strict requirements and a more details on the individual static site generator, whereas staticsitegenerators.net is more of a long list of everything static related.

**Comment by anarcat** [comment]
awesome, thanks for the clarification!
